// .md 프롬프트 파일을 backend/prompts/generated.ts 로 묶어 export.
// 이유: wrangler(esbuild) 와 vitest(vite) 가 .md import 처리 방식이 달라
// 양쪽 빌드를 만족시키는 가장 단순한 방법은 .ts 로 미리 변환해 두는 것.
// dev/test/build/deploy 진입 전에 항상 실행한다.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROMPTS_DIR = join(__dirname, '..', 'prompts');
const OUTPUT = join(PROMPTS_DIR, 'generated.ts');

function buildPromptModule() {
  const files = readdirSync(PROMPTS_DIR)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
    .sort();

  const entries = files.map((file) => {
    const id = file.replace(/\.md$/, '');
    const raw = readFileSync(join(PROMPTS_DIR, file), 'utf8');
    return `  ${JSON.stringify(id)}: ${JSON.stringify(raw)},`;
  });

  return [
    '// AUTO-GENERATED by scripts/build-prompts.mjs. Do NOT edit by hand.',
    '// Source: backend/prompts/*.md',
    '',
    'export const PROMPTS: Record<string, string> = {',
    ...entries,
    '};',
    '',
    'export type PromptId = keyof typeof PROMPTS;',
    '',
  ].join('\n');
}

writeFileSync(OUTPUT, buildPromptModule(), 'utf8');
console.log(`prompts: wrote ${OUTPUT}`);
